module.exports = {
    "tom collins": "The ingredients are 2 fluid ounces gin, 2 fluid ounces lemon juice, 1 fluid ounce simple syrup, 1 dash bitters, 1 cup ice cubes, 1/4 cup cold club soda, 1 slice of lemon for garnish, 1 maraschino cherry. Fill a cocktail shaker with ice. Pour in the gin, lemon juice, simple syrup and a dash of bitters. Cover and shake about 15 seconds or until the outside of the container is frosty. Strain into a highball glass full of ice. Top off with club soda and garnish with a lemon slice and maraschino cherry. Enjoy. ... Would you like another recipe?",
    "gin and tonic": "The ingredients are 3 ice cubes, 2 fluid ounces gin, 4 fluid ounces tonic water and 1 lime wedge. Place ice cubes in a glass. Pour gin and tonic water over the ice. Garnish with lime wedge. Enjoy immediately. ... Would you like another recipe?",
    "gimlet": "The ingredients are 2 fluid ounces gin, 2 fluid ounces sweetened lime juice, 1 teaspoon white sugar and 1/2 cup ice. Place sugar in a shallow dish; dip rim of chilled glass into sugar to coat. Put ice into a shaker. Pour gin and lime juice over the ice and shake well. Pour into the sugar rimmed glass. ... Would you like another recipe?",
    "martini": "The ingredients are 8 fluid ounces gin, 1/2 fluid ounce dry vermouth, 1/2 fluid ounce sweet vermouth, 4 cups ice cubes and 4 pimento-stuffed green olives. Fill cocktail shaker with ice cubes. Add 1/2 ounce each dry and sweet vermouth. Shake enough to coat ice and pour off liquid. Add eight ounces gin to coated ice in shaker and shake vigorously. Pour into four chilled Martini glasses, garnish with pimiento-stuffed olive and serve. Enjoy. ... Would you like another recipe?",
    "french 75": "The ingredients are cracked ice, 2 fluid ounces gin, 1 teaspoon simple syrup, 1/2 fluid ounce lemon juice, 5 fluid ounces brut chilled champagne and 1 slice of lemon, which is optional. Chill shaker and glass (champagne flute or collins glass) in the freezer. Add ice to shaker. Pour gin, simple syrup, and lemon juice into shaker. Shake well. Fill chilled glass half full of ice, then strain cocktail into the glass. Top with champagne and garnish with a lemon slice. Enjoy. ... Would you like another recipe?",
    "gin rickey": "The ingredients are cracked ice, 1 jigger or 1 and a half fluid ounce dry gin, 1 juiced lime, 1/2 teaspoon superfine sugar, seltzer water and 1 slice of lime. Fill a highball glass 3/4 full with ice. Pour in gin, lime juice, and sugar. Stir, and fill remainder of the glass with seltzer water. Garnish with a lime slice. Enjoy. ... Would you like another recipe?",
    "negroni": "The ingredients are 1 and half fluid ounce gin, 1 fluid ounce Campari and 1 fluid ounce sweet vermouth. Combine all ingredients in a mixing glass with ice. Stir. Strain into chilled cocktail glass or over ice. Garnish with an orange twist and enjoy. ... Would you like another recipe?",
    "vesper": "2 fluid ounces gin, 1 fluid ounce vodka and a half fluid ounce Lillet. Combine all ingredients in a mixing glass with ice. Stir. Strain into a chilled cocktail glass. Garnish with a thin orange and lemon curl. Enjoy. ... Would you like another recipe?"
};
